{% set name = "yappi" %}
{% set version = "0.99" %}
{% set hash_type = "sha256" %}
{% set hash = "7a81d7975eeccfaa235448b63aece052e9417f7e0f7862b827dba21be0218b22" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - yappi = yappi:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - yappi

  commands:
    - yappi --help

about:
  home: https://github.com/sumerc/yappi
  license: MIT
  # license file not available in package, see:
  # https://bitbucket.org/sumerc/yappi/pull-requests/27
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Yet Another Python Profiler'
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
