{% set version = "1.6.10" %}

package:
  name: yappi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yappi/yappi-{{ version }}.tar.gz
  sha256: 463b822727658937bd95a7d80ca9758605b8cd0014e004e9e520ec9cb4db0c92

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - yappi = yappi:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=44
  run:
    - python

test:
  requires:
    - pip
  imports:
    - yappi
  commands:
    - pip check
    - yappi --help


about:
  home: https://github.com/sumerc/yappi
  license: MIT
  license_file: LICENSE
  summary: Yet Another Python Profiler
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
