{% set name = "yappi" %}
{% set version = "1.2.1" %}
{% set hash_type = "sha256" %}
{% set hash = "81c420480161e96b28372fc027a162a28785cdba81aaf45c52cdf5536abbd6fb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  entry_points:
    - yappi = yappi:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - yappi

  commands:
    - yappi --help

about:
  home: https://bitbucket.org/sumerc/yappi
  license: MIT
  # license file not available in package, see:
  # https://bitbucket.org/sumerc/yappi/pull-requests/27
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Yet Another Python Profiler'
  license_family: MIT
  dev_url: https://bitbucket.org/sumerc/yappi

extra:
  recipe-maintainers:
    - nicoddemus
