{% set name = "yappi" %}
{% set version = "1.3.2" %}
{% set hash = "a51d3e6e5563cc74b5bb82ed6e7bd44a9c1a7eae3d97e4d52e9465edb3a8da8d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  entry_points:
    - yappi = yappi:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - yappi

  commands:
    - yappi --help

about:
  home: https://github.com/sumerc/yappi
  license: MIT
  # license file not available in package, see:
  # https://bitbucket.org/sumerc/yappi/pull-requests/27
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Yet Another Python Profiler
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
