{% set version = "1.6.0" %}

package:
  name: yappi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/y/yappi/yappi-{{ version }}.tar.gz
  sha256: a9aaf72009d8c03067294151ee0470ac7a6dfa7b33baab40b198d6c1ef00430a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - yappi = yappi:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools >=44
  run:
    - python

test:
  requires:
    - pip
  imports:
    - yappi
  commands:
    - pip checkss
    - yappi --help


about:
  home: https://github.com/sumerc/yappi
  license: MIT
  license_file: LICENSE
  summary: Yet Another Python Profiler
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
